modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://gitee.com/scrambled_egg_with_eek/alltheimbaium/issues"
license="${mod_license}"
logoFile="modIcon.png"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://gitee.com/scrambled_egg_with_eek/alltheimbaium/raw/master/update.json"
    displayURL="https://gitee.com/scrambled_egg_with_eek/alltheimbaium"
    authors="${mod_authors}"
    description='''
      ${mod_description}
      '''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"